workplace_assistant:
  resources_servers:
    workplace_assistant:
      entrypoint: app.py
      domain: agent
      verified: false
      description: Workplace assistant multi-step tool-using environment
      value: Improve multi-step tool use capability
workplace_assistant_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      max_steps: 6
      resources_server:
        type: resources_servers
        name: workplace_assistant
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
        - name: train
          type: train
          jsonl_fpath: resources_servers/workplace_assistant/data/train.jsonl
          huggingface_identifier:
            repo_id: nvidia/Nemotron-RL-agent-workplace_assistant
            artifact_fpath: train.jsonl
          license: Apache 2.0
        - name: validation
          type: validation
          jsonl_fpath: resources_servers/workplace_assistant/data/validation.jsonl
          huggingface_identifier:
            repo_id: nvidia/Nemotron-RL-agent-workplace_assistant
            artifact_fpath: validation.jsonl
          license: Apache 2.0
        - name: example
          type: example
          jsonl_fpath: resources_servers/workplace_assistant/data/example.jsonl